appName: test_scala_apps

domain: bortnichuk.com

frontend:
  name: frontend-scala
  image: dbortnichuk/frontend_scala:latest
  apiVersion: v1
  port: 9100
  nodePort: 30100
  replicas:
    min: 1
    max: 4

backend:
  name: backend-scala
  image: dbortnichuk/backend_scala:latest
  apiVersion: v1
  port: 9090
  nodePort: 30090
  replicas:
    min: 1

mysql:
  name: mysql
  image: dbortnichuk/db-mysql-test:8.0.26
  port: 3306
  nodePort: 30306
  replicas:
    min: 1
    max: 2

