apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend-scala-service
  labels:
    name: frontend-scala-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: 8080
      port: 8080
      protocol: TCP
      name: {{ .Release.Name }}-listener
  selector:
    name: {{ .Release.Name }}-frontend-scala