apiVersion: v1
kind: Service
metadata:
  name: db-mysql-clusterip
  labels:
    name: db-mysql-clusterip
spec:
  type: ClusterIP
  ports:
    - targetPort: 3306
      port: 3306
      protocol: TCP
  selector:
    name: db-mysql