apiVersion: v1
kind: ConfigMap
metadata:
  name: shared
data:
  # property-like keys; each key maps to a simple value

  # backend service name will be used as internal DNS name of the service
  BACKEND_TARGET_HOST: "backend-scala-clusterip"
  BACKEND_TARGET_PORT: "9090"

  # file-like keys
  shared.properties: |
    somecontext.key1=value1
    somecontext.key2=value2

#  DB_MYSQL_HOST: "mysql-clusterip"
  DB_MYSQL_HOST: "mysql-stateful-0.mysql-headless.default.svc.cluster.local"
  DB_MYSQL_PORT: "3306"