apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-path
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /{{ .Values.frontend.apiVersion }} # /frontend -> /v1
    kubernetes.io/ingress.class: "nginx" # for nginx in AWS
spec:
  rules:
    - host: www.{{ .Values.domain }}
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-clusterip
                port:
                  number: {{ .Values.frontend.port }}
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-clusterip
                port:
                  number: {{ .Values.backend.port }}
