apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-host
  annotations:
    kubernetes.io/ingress.class: "nginx" # for nginx in AWS
spec:
  rules:
    - host: frontend.{{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.frontend.apiVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-clusterip
                port:
                  number: {{ .Values.frontend.port }}
    - host: backend.{{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.backend.apiVersion }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-clusterip
                port:
                  number: {{ .Values.backend.port }}
    - host: protected.{{ .Values.domain }}
      http:
        paths:
          - path: /{{ .Values.frontend.apiVersion }}/protected
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-clusterip
                port:
                  number: {{ .Values.frontend.port }}
