apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-headless
  labels:
    name: {{ .Values.mysql.name }}-headless
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.mysql.port }}
      port: {{ .Values.mysql.port }}
      protocol: TCP
  selector:
    name: {{ .Values.mysql.name }}-stateful
  clusterIP: None # by setting this turn this clusterip service into a headless service