apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}-clusterip
  labels:
    name: {{ .Values.mysql.name }}-clusterip
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.mysql.port }}
      port: {{ .Values.mysql.port }}
      protocol: TCP
  selector:
    name: {{ .Values.mysql.name }}